// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-BsQCJVuCmQnQUZ-qLNKMv6SJJapi0Hs',
    appId: '1:612451033750:web:160290d28b74ffb39dd8b7',
    messagingSenderId: '612451033750',
    projectId: 'p2p-money-lending-app',
    authDomain: 'p2p-money-lending-app.firebaseapp.com',
    storageBucket: 'p2p-money-lending-app.appspot.com',
    measurementId: 'G-8K603RB13C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU2-UyqySETVDt_9UGoNyEaAWH8flNFq8',
    appId: '1:612451033750:android:ebf0a1cefba8c5ca9dd8b7',
    messagingSenderId: '612451033750',
    projectId: 'p2p-money-lending-app',
    storageBucket: 'p2p-money-lending-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1kmtGDmu3A5hqps_TIDEr8Ksb-9vQBGs',
    appId: '1:612451033750:ios:632cac1ba955f7c39dd8b7',
    messagingSenderId: '612451033750',
    projectId: 'p2p-money-lending-app',
    storageBucket: 'p2p-money-lending-app.appspot.com',
    iosBundleId: 'com.example.p2pMoneyLendingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1kmtGDmu3A5hqps_TIDEr8Ksb-9vQBGs',
    appId: '1:612451033750:ios:632cac1ba955f7c39dd8b7',
    messagingSenderId: '612451033750',
    projectId: 'p2p-money-lending-app',
    storageBucket: 'p2p-money-lending-app.appspot.com',
    iosBundleId: 'com.example.p2pMoneyLendingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-BsQCJVuCmQnQUZ-qLNKMv6SJJapi0Hs',
    appId: '1:612451033750:web:279986d78c6cdb629dd8b7',
    messagingSenderId: '612451033750',
    projectId: 'p2p-money-lending-app',
    authDomain: 'p2p-money-lending-app.firebaseapp.com',
    storageBucket: 'p2p-money-lending-app.appspot.com',
    measurementId: 'G-WV7G1QFLTE',
  );
}
